### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by batristio** [ifedapoolarewaju/igdm#406]
The message I'm getting from running the IGDM inside the terminal:
```
Error: Cannot find module '/tmp/.mount_IGdm-2Gt6D6v/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

**Comment by emixcopec** [comment]
I have the same problem
emix@emix-Lenovo-V110-14IAP:~$ ./igdm.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_igdm.A3HZJxo/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
emix@emix-Lenovo-V110-14IAP:~$

**Comment by emixcopec** [comment]
I managed to install it by downloading the .deb package instead of the .appimage, I leave here the link:
https://github.com/ifedapoolarewaju/igdm/releases
Select the package that suits you according to the architecture of your system.

**Comment by TeoColuccio** [comment]
even for me the same problem...

**Comment by batristio** [comment]
Nice one @emixcopec. I found that if I set up the project for development - like install Node.js, run npm install and then npm start I am actually able to use it. Cheers!

**Comment by baptx** [comment]
The deb file (https://github.com/ifedapoolarewaju/igdm/issues/349#issuecomment-396568474) was working on Ubuntu 16.04 LTS without installing it by extracting the archive content but since I upgraded to Ubuntu 18.10, there is an error "Segmentation fault (core dumped)" with the same version 2.5.1 and even the latest version 2.5.4.
Now the AppImage file has a segmentation fault also. The only solution to make it work for me is to build the source code with "npm install" and start the program with "npm start" (I also had to do "npm uninstall electron" and "npm install electron" because the GUI was not displayed).
